catalog/urls.py
from .import views
from django.urls import path

urlpatterns = [
    path('',views.index,name='index'),
    path('books/',views.BookListView.as_view(),name= 'books'),
    path('authors/',views.AuthorListView.as_view(),name='authors'),
    path('genres/',views.GenreListView.as_view(),name='genres'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name="book_detail"),
    path('author/<int:pk>/',views.AuthorDetailView.as_view(),name="author_detail"),
    path('poet/<int:author_id>/', views.author_book_list_view, name="poet_detail"),
    path('myborrowed/',views.LoanedCopiesByUserListView.as_view(),name="my_borrowed"),
    path('books/myborrowed/', views.loaned_book_by_user, name = 'loaned_to_user'),
    path('genre/<int:pk>/',views.GenreDetailView.as_view(),name="genre_detail"),
    path('allborrowed/',views.LoanedBookListView.as_view(),name="all_loaned_book"),
    path('books/allborrowed/',views.all_loaned_books,name="all_borrowed_book"),
    path('copy/<uuid:pk>/renew/', views.renew_book, name = "renew_book"),
    path('bookcopy/<uuid:pk>/renew/', views.renew_bookcopy, name="renew_bookcopy"),
    path('author/create/', views.AuthorCreate.as_view(), name = 'author_create'),
    path('author/update/<int:pk>/',views.AuthorUpdate.as_view(),name='author_update'),
    path('author/delete/<int:pk>/',views.AuthorDelete.as_view(),name='author_delete'),
    path('book/create/',views.BookCreate.as_view(),name='book_create'),
    path('book/update/<int:pk>/',views.BookUpdate.as_view(),name='book_update'),
    path('book/delete/<int:pk>/',views.BookDelete.as_view(),name='book_delete'),



]

loclib/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/',include('catalog.urls')),
    path('accounts/',include("django.contrib.auth.urls")),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
import datetime

# Create your models here.


class Author(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    birth_date = models.DateField(blank=True, null=True)
    death_date = models.DateField(blank=True, null=True, verbose_name='died')
    profile = models.TextField(max_length=2080, blank=True, null=True)

    class Meta:
        ordering = ['first_name', 'last_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse('author_detail',args = [str(self.id)])


class Genre(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre_detail',args=[str(self.id)])


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author,on_delete=models.SET_NULL,null=True,blank=True)
    genre = models.ManyToManyField(Genre)
    summary = models.TextField(max_length=2060, blank=True, null=True)
    isbn = models.CharField('isbn',max_length=255, unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book_detail',args=[str(self.id)])

    def display_no_copies(self):
        return BookCopy.objects.filter(book = self).count()

    display_no_copies.short_description = 'copies'

    def display_genres(self):
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genres.short_description = 'Genres'

    
class BookCopy(models.Model):
    book = models.ForeignKey(Book,on_delete=models.RESTRICT)
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    imprint =models.CharField(max_length=280)

    LOAN_STATUS = (
        ('a','Availability'),
        ('o','On Loan'),
        ('m','Maintainance'),
        ('r','Reserved')
    )

   
    status = models.CharField(max_length=1,default='m',choices=LOAN_STATUS)
    due_back = models.DateField(blank=True, null=True)
    borrower = models.ForeignKey(User,on_delete= models.SET_NULL,null= True, blank= True)

    class Meta:
        permissions =(
            ('can_mark_returned','set book as returned'),
            ('can_renew','extend renewal date')
        )
        
                
    def __str__(self):
        return f'{self.book} {self.id}'

    def is_overdue(self):
        return self.due_back and datetime.date.today() > self.due_back

catalog/forms.py
from .models import BookCopy
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class RenewBookForm(forms.Form):
    renew_date = forms.DateField(help_text= "provide a future date within next 4 weeks",)


    def clean_renew_date(self):
        data = self.cleaned_data['renew_date']
        if data < datetime.date.today():
            raise ValidationError(_('its not a future date'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('date must be within 4 weeks'))

        return data
    

class BookRenewModelForm(forms.ModelForm):
    def cleaned_due_back(self):
        data = self.cleaned_data['due_back']
        if data < datetime.date.today():
            raise ValidationError(_("You cannot extend upto a past date"))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("You cannot extend beyong 4 weeks"))
        return data 
    
    class Meta:
        model = BookCopy
        fields =  ['due_back']
        labels =  {'due_back': 'Renewal Date'}
        help_texts = {'due_back': _("Please enter a future date within next 4 weeks")}

     

 

catalog/views.py
import datetime
from typing import ContextManager
from django.contrib.auth.models import Permission
from django.db import models
from django.db.models.base import Model
from django.forms.forms import Form
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Book,BookCopy,Author,Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from .forms import RenewBookForm,BookRenewModelForm
from django.urls import reverse,reverse_lazy



# Create your views here.


class BookListView(generic.ListView):
    model = Book
    paginate_by= 10
    context_object_name= "books"


class AuthorListView(generic.ListView):
    model = Author
    paginate_by =8
    context_object_name = "authors"


class GenreListView(generic.ListView):
    model = Genre
    paginate_by=8
    context_object_name = "genres"


class BookDetailView(generic.DetailView):
    model = Book
    
class AuthorDetailView(generic.DetailView):
    model = Author


class GenreDetailView(generic.DetailView):
    model = Genre

def index(request):
    num_books = Book.objects.all().count()
    num_authors = Author.objects.all().count()
    num_copies = BookCopy.objects.all().count()
    num_copies_available = BookCopy.objects.filter(status__exact='a').count 
    
    num_visits = request.session.get("num_visits",0) 
    num_visits += 1
    request.session["num_visits"]= num_visits


    context = {
        'num_books':num_books,
        'num_authors':num_authors,
        'num_copies':num_copies,
        'num_copies_available':num_copies_available,
        'num_visits': num_visits
    }

    return render(request,'index.html',context = context)


def author_book_list_view(request, author_id):
   author = Author.objects.get(pk = author_id)
   books = Book.objects.filter(author= author)

   context = {
       'author': author,
       'books': books
   }

   return render(request, "catalog/poet_detail.html", context=context)


class  LoanedCopiesByUserListView(LoginRequiredMixin,generic.ListView):
    models = BookCopy
    paginate_by = 10
    context_object_name = 'copies'
    template_name = "catalog/loaned_copies_by_user.html"

    def get_queryset(self):
        return BookCopy.objects.filter(borrower = self.request.user).filter(status = "o").order_by('due_back')


@login_required
def loaned_book_by_user(request):
    copies = BookCopy.objects.filter(borrower = request.user).filter(status = 'o').order_by('due_back')

    context = {'copies': copies}

    return render(request, "catalog/loaned_copies_by_user.html", context=context)


class LoanedBookListView(PermissionRequiredMixin,generic.ListView):
    model =  BookCopy
    permission_required = ('catalog.can_renew')
    paginate_by = 10
    context_object_name ='copies'
    template_name = "catalog/all_loaned_book.html"


    def get_queryset(self):
        return BookCopy.objects.filter(status = 'o').order_by('-due_back')


@login_required
@permission_required('catalog.can_renew', raise_exception=True)
def all_loaned_books(request):
    copies = BookCopy.objects.filter(status = 'o').order_by('due_back')
  

    context = {"copies": copies}


    return render(request,"catalog/all_loaned_book.html",context = context)

@login_required
@permission_required('catalog.can_renew', raise_exception=True)
def renew_book(request,pk):
    copy = get_object_or_404(BookCopy,pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            copy.due_back = form.cleaned_data['renew_date']
            copy.save()
            return HttpResponseRedirect( reverse("all_loaned_book"))
    else:
        proposed_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renew_date':proposed_date})

    context = {'form': form, 'copy': copy}
    return render(request, "catalog/book_renew.html", context=context)


def renew_bookcopy(request, pk):
   copy =  get_object_or_404(BookCopy,pk = pk)
   if request.method == 'POST':
       form = BookRenewModelForm(request.POST)
       if form.is_valid():
           copy.due_back = form.cleaned_data['due_back']
           copy.save()
           return HttpResponseRedirect(reverse('all_loaned_book'))
   else:
        proposed_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = BookRenewModelForm(initial={'due_back': proposed_date})
    
   context ={'copy':copy,'form':form}

   return render(request,"catalog/book_renew.html",context = context) 


class AuthorCreate(generic.CreateView):
    model = Author
    template_name = 'catalog/author_create.html'
    fields = ['first_name', 'last_name', 'birth_date', 'death_date']

class AuthorUpdate(generic.UpdateView):
    model = Author
    template_name = "catalog/author_update.html"
    fields = ['first_name','last_name','birth_date','death_date']
   

class AuthorDelete(generic.DeleteView):
    model =Author
    template_name ="catalog/author_delete.html"
    success_url = reverse_lazy('authors')

class BookCreate(PermissionRequiredMixin, generic.CreateView):
    model = Book
    template_name = "catalog/book_create.html"
    fields = ['title','author','genre','isbn','summary']
    permission_required = ('catalog.can_renew',)


class BookUpdate(generic.UpdateView):
    model = Book
    template_name = "catalog/book_update.html"
    fields=['title','author','genre','isbn','summary']


class BookDelete(generic.DeleteView):
    model = Book
    template_name = "catalog/book_delete.html"
    success_url = reverse_lazy('books')

catalog/templates/catalog/all_loaned_book.html
{% extends "base_generic.html" %}

{% block title %}
<title>ধারের সব বই</title>
{% endblock %}

{% block content %}

<h1>লোনে আছে সমস্ত বইয়ের তালিকাঃ</h1> 
<hr>

{% for copy in copies %}

<h4>{{copy.book}}</h4>
<ul>
    <li><strong>সদস্যের নামঃ </strong>{{copy.borrower}}</li>
    <li><strong>আইডি: </strong>{{copy.id}}</li>
    <li><strong>আইএসবিএনঃ </strong>{{copy.book.isbn}}</li>
    <li><strong>জমা দেয়ার তারিখঃ </strong>{{copy.due_back}}</li>
    <li><strong>মুদ্রনঃ </strong>{{copy.imprint}}</li>
    <li><strong>মেয়াদঃ </strong>{% if copy.is_overdue %} ওভারডিউ {% endif %}</li>
    

</ul>
{% empty %}

<p>দেখানোর মত কোনো বই পেলাম না।</p>

{% endfor %}







{% endblock %}

catalog/templates/catalog/author_create.html
{% extends "base_generic.html" %}

{% block title %} <title>Create Author</title> {% endblock %}

{% block content %}
<h1>Create Author</h1>
<hr>
<form action="" method="POST">
{% csrf_token %}
<table>{{form.as_table}}</table><br>
<input type="submit" value="Create">
</form>

{% endblock %}

catalog/templates/catalog/author_delete.html
{% extends "base_generic.html" %}

{% block title %} <title>Delete Author</title> {% endblock %}
{% block content  %}
<h1>Delete Author?</h1><hr>
<p>Are you sure you wanna delete the author : {{author}}</p><br>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% block title %}

<title>লেখক</title>

{% endblock %}

{% block content %}

<h1 id="atitle">যাদের লেখা বই পড়তে পারবেন</h1>
<hr>

{% for author in authors %}
<ul>
    <li><a href="{{author.get_absolute_url}}">{{author}}</a> ( {{author.birth_date}} - {{author.death_date}} ) </li>
</ul>

{% empty %}
<p>দেখানোর মত কোনো লেখক পেলাম না</p>
{% endfor %}




{% endblock %}

catalog/templates/catalog/author_update.html
{% extends "base_generic.html" %}

{% block title %} <title>update Author</title> {% endblock %}

{% block content %}

<h1>Update Author</h1>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    <table>{{form.as_table}} </table> <br>
    <input type="submit" value="Update">
</form>
{% endblock %}

catalog/templates/catalog/book_create.html
{% extends "base_generic.html" %}
{% block title %} <title>Create Book</title> {% endblock %}

{% block content %}
<h1>Create Book</h1>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    <table>{{form.as_table}}</table><br>
    <input type="submit" value="Create" >
</form>

{% endblock %}

catalog/templates/catalog/book_delete.html
{% extends "base_generic.html" %}
{% block title %} <title>Delete Book</title> {% endblock %}
{% block content  %}

<h1>Delete Book</h1> <hr>
<p>Are you sure you wanna delete the book :{{book}}</p><br>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" >
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% block title %}

<title>{{book}}</title>

{% endblock %}

{% block content %}
<h1 id="bname"><strong>{{book}}</strong></h1>
<hr id="ts">
 <ul>
     <li><strong>কোন বই ?  </strong> {{book}}</li>
     <li><strong>কে লিখেছেন ?  </strong> {{book.author}}</li>
     <li><strong>কোন জনরা ?  </strong> {{book.genre.all|join:", "}}</li>
     <li><strong>আইডি নং ?  </strong> {{book.isbn}}</li>

 </ul>
<br>
<h5>বইটা নিয়ে দুইটা কথা</h5>
<p>====================================</p>

<p>{{book.summary}}</p>


{% endblock %}

catalog/templates/catalog/book_renew.html
{% extends "base_generic.html" %}

{% block title %} <title>Renew Book</title> {% endblock %}
{% block content %}

<h1>বই জমা দেয়ার তারিখ বর্ধিত করুন</h1>
<hr>

<form action="" method="POST">
{% csrf_token %}

<table>
    {{form.as_table}}
</table>
<br>
<input type="submit" value="জমা দিন">

</form>

{% endblock %}

catalog/templates/catalog/book_update.html
{% extends "base_generic.html" %}
{% block title %} <title>Update Book</title> {% endblock %}

{% block content %}

<h1>Update Book</h1><hr>
<form action="" method="POST">
    {% csrf_token %}
    <table>{{form.as_table}}</table><br>
    <input type="submit" value="Update">
</form>

{% endblock %}

catalog/templates/catalog/genre_detail.html
{% extends "base_generic.html" %}
{% block title %}

<title>{{genre}}</title>

{% endblock %}

{% block content %}

<h1>{{genre}}</h1>
<hr>
<h5>এই জনরার যেসব বই পড়তে পারেনঃ </h5>
<br>
{% for book in genre.book_set.all %}
<ul>
    <li><a href="{{book.get_absolute_url}}">{{book}} </a> ( {{book.author}} ) </li>
</ul>
{% empty %}
<p>দেখানোর মত কোন বই পেলাম না</p>
{% endfor %}
{% endblock %}

catalog/templates/catalog/genre_list.html
{% extends "base_generic.html" %}

{% block title %}

<title>জনরা</title>

{% endblock %}

{% block content %}
<h1 id="gtitle">যেসব জনরার বই পাবেন</h1>
<hr>
{% for genre in genres %}

<ul>
<li><a href="{{genre.get_absolute_url}}">{{genre}}</a></li>
</ul>

{% empty %}
    <p>দেখানোর মত কোনো জনরা পেলাম না</p>
{% endfor %}

{% endblock %}

catalog/templates/catalog/loaned_copies_by_user.html
{% extends "base_generic.html" %}

{% block title %}

<title>আমার বইগুলো</title>

{% endblock %}


{% block content %}

<h1>আমার বইএর তালিকাঃ</h1> 
<hr>
<h4>সদস্যের নামঃ {{user.get_username}}</h4>

{% for copy in copies %}
<h5><strong>{{copy.book}}</strong></h5>
<ul>
    <li> আইডি  {{copy.id}}</li>
    <li class="{% if copy.is_overdue %} text-danger {% endif %}"> জমা দেবার তারিখ  {{copy.due_back}}</li>
</ul>
<hr>
{% empty %}

<p>দেখানোর মত কোনো বই পেলেম না।</p>

{% endfor %}

{% endblock %}

catalog/templates/catalog/poet_detail.html
{% extends "base_generic.html" %}

{% block title %}

<title>{{author}}</title>

{% endblock %}

{% block content %}

<h1>{{author}}</h1>
<hr>

<ul>
    <li><strong>নাম: </strong>{{author}}</li>
    <li><strong>জন্ম তারিখ: </strong>{{author.birth_date}}</li>
    <li><strong>মৃত্যু তারিখ: </strong>{{author.death_date}}</li>
       
</ul>
<h3>লেখক পরিচিতিঃ</h3>
<p>====================================</p>

<p>{{author.profile}}</p>

<h3 id="abookh">তার যেসব বই এখানে পাবেনঃ </h3>
<p id="ud">________________________________________________________</p>

{% for book in books %}

<ul>
    <li><a href="{{book.get_absolute_url}}">{{book}}</a></li>
</ul>
{% empty %}
<p>দেখানোর মত কোনো বই পেলাম না</p>
{% endfor %}

{% endblock %}